### ISSUE TITLE
python2.7安装mayavi报错

### ISSUE THREAD

**Issue by Simpleforever** [HViktorTsoi/ACSC#12]
您好，请问您在使用mayavi进行三维点云的可视化的时候是使用的python2.7吗？我使用pip安装mayavi时遇到了以下问题：
Requirement already satisfied: mayavi in ./anaconda3/envs/acsc2/lib/python2.7/site-packages/mayavi-4.5.0-py2.7-linux-x86_64.egg (4.5.0)
Requirement already satisfied: apptools in ./anaconda3/envs/acsc2/lib/python2.7/site-packages (from mayavi) (5.1.0)
ERROR: Package 'apptools' requires a different Python: 2.7.18 not in '>=3.6'
请问您有遇到过此类问题吗？如果没有的话，您有相关python2.7安装mayavi的教程吗？谢谢！

**Comment by HViktorTsoi** [comment]
您好, 在我们本地mayavi的安装环境是python3.6; 另外mayavi是可选依赖,不安装这个库也可以实现完整的标定过程,mayavi只是用来做可视化;

这里找到一个跟您类似的问题 https://stackoverflow.com/questions/61863309/package-requires-a-different-python-2-7-17-not-in-3-6-1-while-setting-up-pr
