### ISSUE TITLE
用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因

### ISSUE THREAD

**Issue by alsosos** [HViktorTsoi/ACSC#2]
python3 calibration.py --config ./configs/sample.yaml

Calculating frame: 0 / 6
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "calibration.py", line 780, in corner_detection_task
    ROI_pc = locate_chessboard(pc)
  File "calibration.py", line 389, in locate_chessboard
    pc = utils.voxelize(pc, voxel_size=configs['calibration']['RG_VOXEL'])
  File "/home/zehao/catkin_ws/src/ACSC/utils.py", line 129, in voxelize
    cloud.from_array(pc.astype(np.float32))
  File "pcl/pxi/PointCloud_PointXYZI_180.pxi", line 158, in pcl._pcl.PointCloud_PointXYZI.from_array
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibration.py", line 940, in <module>
    calibration(keep_list=None)
  File "calibration.py", line 870, in calibration
    corners_world, final_cost, corners_image = detection_result[idx].get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AssertionError

**Comment by HViktorTsoi** [comment]
您好 这个是因为采的数据的维度(N x 5)和calibration.py需要的维度(N x 4) 不一致导致的;

目前最快的修复方法是在 `calibration.py` 的 [第819行](https://github.com/HViktorTsoi/ACSC/blob/590eacd75fdbe19bf3c0696cded9a495493de17d/calibration.py#L819) 后边 加上这句代码:

`full_pc = full_pc[:, :4]`

我们也会尽快修复这个bug并更新代码到repo上

**Comment by HViktorTsoi** [comment]
代码已更新, 可以把最新的calibration.py pull下来

**Comment by alsosos** [comment]
已收到！但是好像除了标定板贴合效果好 其他点云贴合不好，这是我标定板所处的环境不好原因造成的嘛！很感谢你！

---原始邮件---
发件人: "KINO"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 晚上6:13
收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;;
主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2)




 
代码已更新, 可以把最新的calibration.py pull下来

**Comment by alsosos** [comment]
还有就是一开始相机驱动启动不了 我是Ubuntu18.04的好像源码参数读不进去😂



---原始邮件---
发件人: "KINO"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 晚上6:13
收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;;
主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2)




 
代码已更新, 可以把最新的calibration.py pull下来

**Comment by HViktorTsoi** [comment]
> 已收到！但是好像除了标定板贴合效果好 其他点云贴合不好，这是我标定板所处的环境不好原因造成的嘛！很感谢你！
> […](#)
> ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月9日(周三) 晚上6:13 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 代码已更新, 可以把最新的calibration.py pull下来 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您这边在标定的时候把标定板放置了几个不同位置? 建议多放置几个位置试试;

另外这个问题看起来更像是相机本身内参标定的不准确导致的问题, 方便将您的数据(包括pcds/ images/ ROIs/ intrinsic文件 distortion文件) 打包发我debug看一下嘛, 邮箱是cuijiahetony@live.com

**Comment by HViktorTsoi** [comment]
> 还有就是一开始相机驱动启动不了 我是Ubuntu18.04的好像源码参数读不进去
> […](#)
> ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月9日(周三) 晚上6:13 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 代码已更新, 可以把最新的calibration.py pull下来 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这个问题描述的不太清楚... 您是说calibration_data_collection这个工具在启动之后没有图像显示嘛? 确定一下在roslaunch的时候`image-topic`给定的是正确参数, 就是相机图像对应的topic(可以先在rviz里看,确定这个topic能收到图像)

如果是相机本身驱动的问题..这个要看对应相机驱动的文档

**Comment by alsosos** [comment]
想请问下ROIs文件的作用，因为我的相机驱动打不开，图像是用vlc截的 ROIs下就没有获取到数据！



---原始邮件---
发件人: "KINO"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 晚上7:10
收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;;
主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2)




  
已收到！但是好像除了标定板贴合效果好 其他点云贴合不好，这是我标定板所处的环境不好原因造成的嘛！很感谢你！
 …
 ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月9日(周三) 晚上6:13 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 代码已更新, 可以把最新的calibration.py pull下来 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您这边在标定的时候把标定板放置了几个不同位置? 建议多放置几个位置试试;
 
另外这个问题看起来更像是相机本身内参标定的不准确导致的问题, 方便将您的数据(包括pcds/ images/ ROIs/ intrinsic文件 distortion文件) 打包发我debug看一下嘛, 邮箱是cuijiahetony@live.com

**Comment by alsosos** [comment]
非常感谢！！！现在电脑不在身边&nbsp; 明天请您帮忙看看！

---原始邮件---
发件人: "KINO"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 晚上7:10
收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;;
主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2)




  
已收到！但是好像除了标定板贴合效果好 其他点云贴合不好，这是我标定板所处的环境不好原因造成的嘛！很感谢你！
 …
 ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月9日(周三) 晚上6:13 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 代码已更新, 可以把最新的calibration.py pull下来 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您这边在标定的时候把标定板放置了几个不同位置? 建议多放置几个位置试试;
 
另外这个问题看起来更像是相机本身内参标定的不准确导致的问题, 方便将您的数据(包括pcds/ images/ ROIs/ intrinsic文件 distortion文件) 打包发我debug看一下嘛, 邮箱是cuijiahetony@live.com

**Comment by HViktorTsoi** [comment]
> 想请问下ROIs文件的作用，因为我的相机驱动打不开，图像是用vlc截的 ROIs下就没有获取到数据！
> […](#)
> ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月9日(周三) 晚上7:10 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 已收到！但是好像除了标定板贴合效果好 其他点云贴合不好，这是我标定板所处的环境不好原因造成的嘛！很感谢你！ … ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月9日(周三) 晚上6:13 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 代码已更新, 可以把最新的calibration.py pull下来 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 您这边在标定的时候把标定板放置了几个不同位置? 建议多放置几个位置试试; 另外这个问题看起来更像是相机本身内参标定的不准确导致的问题, 方便将您的数据(包括pcds/ images/ ROIs/ intrinsic文件 distortion文件) 打包发我debug看一下嘛, 邮箱是cuijiahetony@live.com — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

哦哦.... 那标定结果不准有可能就是因为使用了截图而不是保存的图像... 如果截的图和相机本身输出的图像的尺寸和宽高比不一致的话, 相当于相机的内参也被改变了, 最终的结果就是用错误的相机内参去标定正确的雷达-相机外参 , 所以除了标定板之外其他地方都匹配的不好;

对于解决办法, 您这边先确定能在标定过程中看到图像, 并且能保存图像(使用calibration_data_collection保存), 然后再重新采集数据并验证标定结果

ROIs目录的数据目前没有用到,留空就可以

**Comment by alsosos** [comment]
好的 感谢解答！



---原始邮件---
发件人: "KINO"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 晚上7:35
收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;;
主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2)




  
想请问下ROIs文件的作用，因为我的相机驱动打不开，图像是用vlc截的 ROIs下就没有获取到数据！
 …
 ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月9日(周三) 晚上7:10 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 已收到！但是好像除了标定板贴合效果好 其他点云贴合不好，这是我标定板所处的环境不好原因造成的嘛！很感谢你！ … ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月9日(周三) 晚上6:13 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 代码已更新, 可以把最新的calibration.py pull下来 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 您这边在标定的时候把标定板放置了几个不同位置? 建议多放置几个位置试试; 另外这个问题看起来更像是相机本身内参标定的不准确导致的问题, 方便将您的数据(包括pcds/ images/ ROIs/ intrinsic文件 distortion文件) 打包发我debug看一下嘛, 邮箱是cuijiahetony@live.com — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
哦哦.... 那标定结果不准有可能就是因为使用了截图而不是保存的图像... 如果截的图和相机本身输出的图像的尺寸和宽高比不一致的话, 相当于相机的内参也被改变了, 最终的结果就是用错误的相机内参去标定正确的雷达-相机外参 , 所以除了标定板之外其他地方都匹配的不好;
 
对于解决办法, 您这边先确定能在标定过程中看到图像, 并且能保存图像(使用calibration_data_collection保存), 然后再重新采集数据并验证标定结果
 
ROIs目录的数据目前没有用到,留空就可以

**Comment by alsosos** [comment]
驱动启动后只能看到鸟瞰图，但是没相机图像界面，rviz也能收到点云图像。请问如何解决

**Comment by HViktorTsoi** [comment]
> 驱动启动后只能看到鸟瞰图，但是没相机图像界面，rviz也能收到点云图像。请问如何解决

您好, 请确定的相机图像的topic是什么, 这个topic是否和您在启动calibration_data_collection.launch的时候传入的参数(`image-topic:=你的相机图像topic`)一致?

可以把启动calibration_data_collection.launch的命令行命令及参数发上来看一下

**Comment by HViktorTsoi** [comment]
> 驱动启动后只能看到鸟瞰图，但是没相机图像界面，rviz也能收到点云图像。请问如何解决

启动calibration_data_collection.launch, 命令行参数是这样的含义
```
roslaunch calibration_data_collection lidar_camera_calibration.launch \                                                                                                                  
config-path:=你本地的ACSC项目目录/configs/data_collection.yaml \
image-topic:=你的相机图像topic \
lidar-topic:=Livox点云的topic \
saving-path:=存放数据的目录
```

**Comment by HViktorTsoi** [comment]
> 驱动启动后只能看到鸟瞰图，但是没相机图像界面，rviz也能收到点云图像。请问如何解决

如果确定相机图像的topic和命令行参数是已知的, 看一下运行lidar_camera_calibration.launch的终端是否有报错信息

**Comment by alsosos** [comment]
请问如何知道图像topic是否发布和图像topci是什么，刚接触不太懂😂😂



---原始邮件---
发件人: "KINO"<notifications@github.com&gt;
发送时间: 2020年12月10日(周四) 晚上10:53
收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;;
主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2)




  
驱动启动后只能看到鸟瞰图，但是没相机图像界面，rviz也能收到点云图像。请问如何解决
  
如果确定相机图像的topic和命令行参数是已知的, 看一下运行lidar_camera_calibration.launch的终端是否有报错信息

**Comment by alsosos** [comment]
请问你是用什么驱动发布topic的 我应该缺少了发布topic的中间环节 网上没找到有关melodic发布相机主题的驱动包



---原始邮件---
发件人: "KINO"<notifications@github.com&gt;
发送时间: 2020年12月10日(周四) 晚上10:49
收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;;
主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2)




  
驱动启动后只能看到鸟瞰图，但是没相机图像界面，rviz也能收到点云图像。请问如何解决
  
您好, 请确定的相机图像的topic是什么, 这个topic是否和您在启动calibration_data_collection.launch的时候传入的参数(image-topic:=你的相机图像topic)一致?
 
可以把启动calibration_data_collection.launch的命令行命令及参数发上来看一下

**Comment by HViktorTsoi** [comment]
> 请问如何知道图像topic是否发布和图像topci是什么，刚接触不太懂
> […](#)
> ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月10日(周四) 晚上10:53 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 驱动启动后只能看到鸟瞰图，但是没相机图像界面，rviz也能收到点云图像。请问如何解决 如果确定相机图像的topic和命令行参数是已知的, 看一下运行lidar_camera_calibration.launch的终端是否有报错信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您用的相机是什么牌子和型号的? 每个品牌相机对应的驱动都不同, 这个要看具体使用的哪个牌子

**Comment by alsosos** [comment]
感谢，请问你最后彩色点云是怎么实现的~



---原始邮件---
发件人: "KINO"<notifications@github.com&gt;
发送时间: 2020年12月10日(周四) 晚上11:03
收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;;
主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2)




  
请问如何知道图像topic是否发布和图像topci是什么，刚接触不太懂
 …
 ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月10日(周四) 晚上10:53 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 驱动启动后只能看到鸟瞰图，但是没相机图像界面，rviz也能收到点云图像。请问如何解决 如果确定相机图像的topic和命令行参数是已知的, 看一下运行lidar_camera_calibration.launch的终端是否有报错信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您用的相机是什么牌子和型号的? 每个品牌相机对应的驱动都不同, 这个要看具体使用的哪个牌子

**Comment by HViktorTsoi** [comment]
> 感谢，请问你最后彩色点云是怎么实现的~
> […](#)
> ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月10日(周四) 晚上11:03 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 请问如何知道图像topic是否发布和图像topci是什么，刚接触不太懂 … ---原始邮件--- 发件人: "KINO"<notifications@github.com&gt; 发送时间: 2020年12月10日(周四) 晚上10:53 收件人: "HViktorTsoi/ACSC"<ACSC@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"alsosos"<583739627@qq.com&gt;; 主题: Re: [HViktorTsoi/ACSC] 用自己录制的pcds文件提示以下错误，相机校准出错，但是用你的pcds文件却可以运行，请问是什么原因 (#2) 驱动启动后只能看到鸟瞰图，但是没相机图像界面，rviz也能收到点云图像。请问如何解决 如果确定相机图像的topic和命令行参数是已知的, 看一下运行lidar_camera_calibration.launch的终端是否有报错信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 您用的相机是什么牌子和型号的? 每个品牌相机对应的驱动都不同, 这个要看具体使用的哪个牌子 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以看一下projection_validation.py里的源码, 就是标定之后, 首先用外参将点云对齐到相机坐标系, 然后再用相机内参投影到深度图, 查找深度图中每个像素对应的相机图像的RGB值,再重新投影回3D空间, 这样得到的就是有XYZRGB多信息的点云了.
