### ISSUE TITLE
请问点云着色效果不是很好是什么原因

### ISSUE THREAD

**Issue by alsosos** [HViktorTsoi/ACSC#5]
![sendpix0](https://user-images.githubusercontent.com/53991982/102582096-d6a65400-413c-11eb-9ad3-5753dcde883f.jpg)

**Comment by alsosos** [comment]
用此项目计算的旋转矩阵和内参矩阵获取点云颜色后，颜色和点云重合情况有些偏差，请问是什么原因？

**Comment by HViktorTsoi** [comment]
您好, 
1. 如果方便的话请把您的数据打包发给我debug(包括pcds/ images/ ROIs/ intrinsic文件 distortion文件), 邮箱是cuijiahetony@live.com

2. 请把检测出来的棋盘格3D角点重投影回图像的结果发一下(就是在运行projection_validation.py之后, 最后出现的几张图像);

3. 确定您的相机内参标定的是准确的;

4. 标定过程中标定板摆放了几个位置?
