### ISSUE TITLE
是否适用于机械式机械雷达

### ISSUE THREAD

**Issue by Simpleforever** [HViktorTsoi/ACSC#7]
请问这种方法的代码适用于机械式激光雷达吗？以及棋盘格标定板材料是特殊定制的吗还是普通的打印的？谢谢！！！

**Comment by HViktorTsoi** [comment]
您好; 我们在robosense的 RS32 和 RS Ruby这类机械雷达上测试过都可以正常标定,LIVOX的各型号都可以正常标定; 更多的型号您这边可以进行尝试; 

标定板用普通的打印纸出来就可以,但是要贴在硬纸板上,并且保证尺寸和形状满足[文档中的要求](https://github.com/HViktorTsoi/ACSC#22-preparing-the-calibration-board).

**Comment by Simpleforever** [comment]
好的谢谢！您好，我在运行python calibration.py --config [./configs/sample.yaml时候出现了以下错误，并且segmentation_ext也按照您的流程安装了，请问您知道可能是什么原因吗？
python calibration.py --config ./configs/sample.yaml
Traceback (most recent call last):
  File "calibration.py", line 27, in <module>
    import segmentation_ext
ImportError: dynamic module does not define module export function (PyInit_segmentation_ext)

**Comment by HViktorTsoi** [comment]
1. 您是否有使用conda? 
2. 运行calibration.py时的python版本是多少?
请首先确保编译安装segmentation_ext的python环境与运行calibration.py的python环境是一致的
3. 请在运行calibration.py之前输入以下命令,
`echo $PYTHONPATH` 
然后把结果贴上来

**Comment by HViktorTsoi** [comment]
另外这个问题之前有人在issue里提过, 和您的情况很像,可以参考这个解决办法
https://github.com/HViktorTsoi/ACSC/issues/1#issuecomment-741894158

**Comment by Simpleforever** [comment]
问题已经解决了，谢谢您的解答！！！
